name: Deployment

env:
  AR_LOCATION: eu
  REGION: europe-southwest1 # Madridoo
  RWX_ACCESS_TOKEN: ${{ secrets.RWX_ACCESS_TOKEN }}


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: push

jobs:

  build_image:

    env:
      NEXT_PUBLIC_API_BASE: 'https://api.errenta.eus'
      CI: true


    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')

    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    environment: gcp

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
      
      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build the image
        run: |
          export COMMIT_TIME=$(git show -s --format=%cI ${GITHUB_SHA})
          export COMMIT_VERSION=$(git describe --always)
          echo $GITHUB_SHA
          echo $COMMIT_TIME
          echo $COMMIT_VERSION
          docker  build --build-arg COMMIT_TIME --build-arg COMMIT_VERSION -t app .
      - name: Push the image tagged with version to the container registry
        run: |
          docker tag app ${{ env.AR_LOCATION }}.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}
          docker push ${{ env.AR_LOCATION }}.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}

  launch_deployment:
    needs: build_image
    environment: gcp
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')

    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' 

      - id: 'Deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'errentanext'
          image: '${{ env.AR_LOCATION }}.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}'
          project_id: ${{ secrets.PROJECT_ID }}
          region: europe-west1
          env_vars: |
           NEXT_PUBLIC_API_BASE='https://api.errenta.eus' 
